### ISSUE TITLE
App speichert das Gießen nicht, wenn ich mich über Google authentisiere

### ISSUE THREAD

**Issue by nkaleidoskop** [CodeforLeipzig/tsb-trees-frontend#1]
## Background: Why this issue? 
Die App registriert oder speichert meine Gieß-Aktion nicht, wenn ich mich über Google authentisiere. Habe zweimal versucht, den hier: https://giessdeinviertel.codeforleipzig.de/search?location=id-28481 zu gießen, einmal  20.4.2021 0:30 Uhr und einmal ca 23:50. Es zeigt kurz an "Begießung eingetragen!" (oder so) und dann taucht es aber nicht auf. Nicht in meinem Gießfortschritt und auch nicht am Baum selbst. Wenn ich über Google eingeloggt bin, zeigt es im Profil auch weder Mail noch Namen an.

Wenn ich es über einen extra registrierten Account mache, klappt alles.

## Deliverables: How to fix the issue?
Als schnellen Workaround könnte man die Option, sich über Google anzumelden, rausnehmen.

## Output: Gain of fixing the issue?
Gerade beim Launch sollte das klappen, damit der anfängliche Enthusiasmus für dieses Projekt erhalten bleibt.

## Issue creation checklist
- [ ] I have attached one of the priority labels `HIGH`, `MIDDLE`, `LOW`
- [ ] I have attached other labels with regard to the issues purpose (i.e.`enhancement`, `bug`, `community feedback`)

**Comment by joergreichert** [comment]
Ja, stimmt, dass mit dem Google Auth hat noch nie so richtig funktioniert, ich habe es jetzt im Auth0 wegkonfiguriert. Danke für den Reminder.
